### PR TITLE
Support NSUserDefaults with suiteName

### PR DESCRIPTION
**Pull request by remstos**
We may need to use NSUserDefaults with app groups (for iOS extension).

### CODE REVIEW

**Comment by wwayne** [comment]
No, I gave up go on using userDefaults because Android doesn't support this...I wanted to build an APP in both platform

**Comment by wwayne** [comment]
Why moving code from `lib/userDefaults` to `userDefaults` ? No need to use babel transform the code first?

**Comment by remstos** [comment]
The packager can take care of this, no ?

**Comment by wwayne** [comment]
Thanks

**Pull request merged**
